# bound.agent.intent.potential
import asyncio
import time
import json
from dataclasses import dataclass
from typing import Any, Dict, Optional

from phase.anchor.config.dphi import dphi_env

from phase.anchor.adapter.eco import EcoAdapter
from phase.epoch.workflow.intent import DvmRpcBridge, NodeIdentity

from arch.topos.workflow import ErrorMessage, StopMessage, Workflow, WorkflowMessage, step
from arch.contract.event.next import generate_parity_triplet
from kernel.dphi.adapter.state import StateAdapter
from kernel.dphi.broker import DphiMethod
from watcher.plane.emitter import get_emitter

log = get_emitter("intent.potential")

@dataclass
class PsiArtifact:
    """
    [Preserved Heuristic State] 
    The initial, non-deterministic execution trajectory generated by the stochastic model.
    """
    suggested_target: str       
    suggested_calldata: str     

@dataclass
class TopologicalIntent:
    """
    [Invariant State Transition Vector] 
    Defines the pure objective manifold of the state transition.
    """
    event_id: str
    target_vm: str             
    input_asset: str           
    target_asset: str          
    expected_spread: int       
    artifact: PsiArtifact      

class IntentIngressMsg(WorkflowMessage): pass
class ShadowSyncMsg(WorkflowMessage): pass
class DvmObservationMsg(WorkflowMessage): pass
class EpochSealMsg(WorkflowMessage): pass
class IntentRecalibrateMsg(WorkflowMessage): pass

class TopologicalIntentWorkflow(Workflow):
    """
    State machine governing the phase transition of stochastic intents.
    🌟 [지연 정산 반영] DVM 섀도우 연산을 위해 에이전트의 Mandate 서명을 생성하고 Capability Token을 발급받아 통신함.
    """
    def __init__(self, intent: TopologicalIntent):
        super().__init__(name=f"TOPO_INTENT [{intent.event_id[:8]}]")
        self.log = log
        self.intent = intent
        self.rpc_bridge = DvmRpcBridge()
        
        self.field_node = NodeIdentity()
        self.shadow_state: Dict[str, Any] = {}
        self.dvm_state_diff: Dict[str, Any] = {}
        
        self.optimal_target: Optional[str] = None
        self.optimal_calldata: Optional[str] = None
        
        self.profit_margin: int = 0
        self.sealed_receipt: Optional[Dict[str, Any]] = None
        
        # 🌟 지연 정산 및 통행권
        self.capability_receipt_id: Optional[str] = None

    async def start(self) -> bool:
        self.log.info(f"[INGRESS] Mapping intent topology: {self.intent.event_id}. Formulating Mandate...")
        self.post_message(IntentIngressMsg())
        await self.run()
        return self.sealed_receipt is not None

    @step
    async def phase_billing_handshake(self, msg: IntentIngressMsg) -> WorkflowMessage:
        """
        🌟 [신규 Phase: 지연 정산 핸드셰이크]
        에이전트가 가스비(ETH) 없이 자신의 키로 Mandate(백지수표)를 서명하여 DPHI에 제출.
        이후 DVM 연산 자원을 소모할 수 있는 Capability Token(영수증)을 획득.
        """
        self.log.info("[PHASE 0] Authorizing Deferred Billing Mandate to DPHI Edge.")
        
        ap2_mandate = EcoAdapter.build_ap2_mandate(
            requester_id=self.field_node.evm_address,
            target_action="shadow_execution",
            max_spend_usdc="100.0",
            signer_key=self.field_node.key
        )
        
        # DPHI RPC(또는 Edge API)에 Mandate 제출 (INIT_EPOCH로 추상화되어 있음)
        init_payload = {
            "action": DphiMethod.INIT_EPOCH.value,
            "topo": 120, "press": 85,
            "mandate": ap2_mandate.model_dump(exclude_none=True)
        }
        
        res = await self.rpc_bridge.request(init_payload)
        if res.get("status") != 200:
            return ErrorMessage(f"Mandate Rejected. Insufficient clearance: {res.get('error')}")
            
        # DPHI가 허가한 오프체인 역량 영수증 ID 획득 (향후 HTTP 헤더에 담길 값)
        self.capability_receipt_id = res.get("data", {}).get("phase_id", "mock_receipt_123")
        self.log.info(f"  └─ Capability Token Acquired: {self.capability_receipt_id}")
        
        return ShadowSyncMsg()

    @step
    async def phase_shadow_projection(self, msg: ShadowSyncMsg) -> WorkflowMessage:
        self.log.info("[PHASE 1] Projecting external state space onto local shadow manifold.")
        
        self.shadow_state = {
            self.intent.artifact.suggested_target: { "balance": "0x_latest_pool_balance", "nonce": 0 },
            self.field_node.pub_hex: { "balance": "0x_mock_jit_liquidity", "nonce": 1 }
        }
        
        # 실제 환경에서는 이 단계에서 self.capability_receipt_id 를 X-X402-Receipt 헤더로 래핑하여 통신함.
        return DvmObservationMsg()

    @step
    async def phase_dvm_solver(self, msg: DvmObservationMsg) -> WorkflowMessage:
        self.log.info("[PHASE 2] Evaluating heuristic artifact against deterministic boundary conditions.")
        
        dvm_payload_hypothesis = {
            "vm_target": self.intent.target_vm,
            "payload": {
                "target_address": self.intent.artifact.suggested_target,
                "calldata": self.intent.artifact.suggested_calldata,
                "gas_limit": 500000,
                "state_snapshot": self.shadow_state
            }
        }
        
        # 🌟 지연 정산 토큰(Receipt) 첨부
        res = await self.rpc_bridge.request({
            "action": "simulate_vm", 
            "payload": dvm_payload_hypothesis,
            "billing_receipt": self.capability_receipt_id
        })
        
        data = res.get("data", {})
        self.profit_margin = int(data.get("state_diff", {}).get("agent_profit_delta", "0x0"), 16)
        
        if res.get("status") != 200 or self.profit_margin < self.intent.expected_spread:
            self.log.warning("[ARTIFACT DEVIATION] Heuristic failed boundary constraints. Initiating deterministic solver for re-calibration...")
            
            recalc_res = await self.rpc_bridge.request({
                "action": "solve_optimal_path",
                "intent": {
                    "input": self.intent.input_asset,
                    "target": self.intent.target_asset,
                    "snapshot": self.shadow_state
                },
                "billing_receipt": self.capability_receipt_id # 🌟 지연 정산 토큰(Receipt) 재사용
            })
            
            if not recalc_res.get("data", {}).get("success"):
                return ErrorMessage("Topological constraints violated: No mathematical path exists within current state bounds.")
                
            data = recalc_res.get("data")
            self.profit_margin = int(data.get("state_diff", {}).get("agent_profit_delta", "0x0"), 16)
            
            self.optimal_target = data.get("optimal_target")
            self.optimal_calldata = data.get("optimal_calldata")
        else:
            self.log.info("[ARTIFACT CONVERGENCE] Heuristic trajectory aligns perfectly with deterministic invariants.")
            self.optimal_target = self.intent.artifact.suggested_target
            self.optimal_calldata = self.intent.artifact.suggested_calldata

        self.dvm_state_diff = data.get("state_diff", {})
        return EpochSealMsg()

    @step
    async def phase_epoch_seal(self, msg: EpochSealMsg) -> WorkflowMessage:
        self.log.info("[PHASE 3] Cryptographic entanglement of phase transition invariants.")
        
        parity = generate_parity_triplet(topo=120, press=85)
        
        seal_payload = StateAdapter.build_seal_epoch_payload(
            parity=parity, 
            parent_nexus_id=0, 
            self_parent_state="genesis",
            repos={
                "intent_id": self.intent.event_id,
                "heuristic_artifact": self.intent.artifact.__dict__,
                "deterministic_vector": self.optimal_calldata,
                "billing_receipt_used": self.capability_receipt_id # 🌟 커널에 영수증 사용 내역 씰링
            }, 
            cached_states={"state_differential": self.dvm_state_diff},
            timestamp=time.time(), 
            signers=[], signatures=[], threshold=0
        )
        
        res = await self.rpc_bridge.request({
            "action": DphiMethod.SEAL_EPOCH.value, 
            "payload": StateAdapter.to_canonical_bytes(seal_payload).decode('utf-8')
        })
        
        if res.get("status") != 200:
            return ErrorMessage(f"Seal generation rejected: {res.get('error')}")
            
        self.sealed_receipt = res.get("data", {})
        return IntentRecalibrateMsg()

    @step
    async def phase_private_relay(self, msg: IntentRecalibrateMsg) -> WorkflowMessage:
        self.log.info("[PHASE 4] Relaying conditioned state transition payload to private execution topology.")
        
        relay_payload = {
            "sealed_hash": self.sealed_receipt.get("hash"),
            "target_address": self.optimal_target,
            "calldata": self.optimal_calldata,
            "execution_condition": {
                "min_profit": self.intent.expected_spread
            }
        }
        
        self.log.info("[RELAY] Dispatching hardened topological payload to isolated consensus network.")
        # await self.rpc_bridge.request({"action": "submit_private_bundle", "payload": relay_payload})
        
        self.log.info("[FINALITY] Topological phase transition complete. State differential matrix materialized.")
        return StopMessage(result=True)

    @step
    async def on_error(self, msg: ErrorMessage) -> WorkflowMessage:
        self.log.error(f"[HALT] Preserving non-convergent state vectors for heuristic re-calibration: {msg.msg}")
        return StopMessage(result=False)