# agent.runtime.protocol.context
## @lineage: ator.driver.protocol.context
## @lineage: agent.protocol.context
from collections.abc import Mapping
from pathlib import Path
from typing import Protocol, Any

from arch.model.conv.security.confirm import ConfirmationPolicyBase
from agent.runtime.conv.security import SecurityAnalyzerBase
from bound.space.action.action import Action, Observation
from bound.space.action.types import ConversationID
from bound.space.action.message import Message

from arch.contract.resolver.secret import SecretValue


class SecretProviderProtocol(Protocol):
    """터미널 등이 환경변수 및 마스킹을 위해 사용하는 시크릿 레지스트리 명세"""
    def get_secrets_as_env_vars(self, command: str) -> dict[str, str]: ...
    def mask_secrets_in_output(self, text: str) -> str: ...

class ToolStateProtocol(Protocol):
    @property
    def secret_registry(self) -> SecretProviderProtocol: ...

class ToolExecutionContextProtocol(Protocol):
    """ActionExecutor 등 도구가 사용하는 최소한의 컨텍스트"""
    @property
    def state(self) -> ToolStateProtocol: ...
    @property
    def workspace(self) -> Any: ...

class AgentCommunicationProtocol(Protocol):
    """외부에서 에이전트와 메시지를 주고받는 입출력 전용 명세"""
    @property
    def id(self) -> ConversationID: ...
    def send_message(self, message: str | Message, sender: str | None = None) -> None: ...
    def ask(self, question: str) -> str: ...

class ExecutionControlProtocol(Protocol):
    """대화의 생명주기와 실행 루프를 제어하는 권한 명세"""
    def run(self) -> None: ...
    def pause(self) -> None: ...
    def close(self) -> None: ...
    def rerun_actions(self, rerun_log_path: str | Path | None = None) -> bool: ...
    def execute_tool(self, tool_name: str, action: Action) -> Observation: ...

class SecurityControlProtocol(Protocol):
    """가드레일, 정책 설정, 사용자 컨펌 및 비밀 데이터 관리 명세"""
    @property
    def is_confirmation_mode_active(self) -> bool: ...
    @property
    def confirmation_policy_active(self) -> bool: ...
    def set_confirmation_policy(self, policy: ConfirmationPolicyBase) -> None: ...
    def set_security_analyzer(self, analyzer: "SecurityAnalyzerBase | None") -> None: ...
    def reject_pending_actions(self, reason: str = "User rejected the action") -> None: ...
    def update_secrets(self, secrets: Mapping[str, SecretValue]) -> None: ...