# adapter.mapper.acp.scheme
## @lineage: bound.adapter.mapper.acp.scheme
MODELS_TO_REMOVE = [
    "AgentClientProtocol",
    "AgentClientProtocol1",
    "AgentClientProtocol2",
    "AgentClientProtocol3",
    "AgentClientProtocol4",
    "AgentClientProtocol5",
    "AgentClientProtocol6",
    "AgentClientProtocol7",
]

RENAME_MAP: dict[str, str] = {
    "AgentResponse1": "AgentResponseMessage",
    "AgentResponse2": "AgentErrorMessage",
    "ClientResponse1": "ClientResponseMessage",
    "ClientResponse2": "ClientErrorMessage",
    "ContentBlock1": "TextContentBlock",
    "ContentBlock2": "ImageContentBlock",
    "ContentBlock3": "AudioContentBlock",
    "ContentBlock4": "ResourceContentBlock",
    "ContentBlock5": "EmbeddedResourceContentBlock",
    "McpServer1": "HttpMcpServer",
    "McpServer2": "SseMcpServer",
    "McpServer3": "AcpMcpServer",
    "RequestPermissionOutcome1": "DeniedOutcome",
    "RequestPermissionOutcome2": "AllowedOutcome",
    "AuthMethod1": "EnvVarAuthMethod",
    "AuthMethod2": "TerminalAuthMethod",
    "SessionConfigOption1": "SessionConfigOptionSelect",
    "SessionConfigOption2": "SessionConfigOptionBoolean",
    "SetSessionConfigOptionRequest1": "SetSessionConfigOptionBooleanRequest",
    "SetSessionConfigOptionRequest2": "SetSessionConfigOptionSelectRequest",
    "SessionUpdate1": "UserMessageChunk",
    "SessionUpdate2": "AgentMessageChunk",
    "SessionUpdate3": "AgentThoughtChunk",
    "SessionUpdate4": "ToolCallStart",
    "SessionUpdate5": "ToolCallProgress",
    "SessionUpdate6": "AgentPlanUpdate",
    "SessionUpdate7": "AgentPlanContentUpdate",
    "SessionUpdate8": "AgentPlanRemovedUpdate",
    "SessionUpdate9": "AvailableCommandsUpdate",
    "SessionUpdate10": "CurrentModeUpdate",
    "SessionUpdate11": "ConfigOptionUpdate",
    "SessionUpdate12": "SessionInfoUpdate",
    "SessionUpdate13": "UsageUpdate",
    "PlanUpdateContent1": "PlanUpdateItems",
    "PlanUpdateContent2": "PlanUpdateFile",
    "PlanUpdateContent3": "PlanUpdateMarkdown",
    "ToolCallContent1": "ContentToolCallContent",
    "ToolCallContent2": "FileEditToolCallContent",
    "ToolCallContent3": "TerminalToolCallContent",
    "CreateElicitationRequest1": "CreateFormElicitationRequest",
    "CreateElicitationRequest2": "CreateUrlElicitationRequest",
    "CreateElicitationResponse1": "AcceptElicitationResponse",
    "CreateElicitationResponse2": "DeclineElicitationResponse",
    "CreateElicitationResponse3": "CancelElicitationResponse",
    "ElicitationFormMode1": "ElicitationFormSessionMode",
    "ElicitationFormMode2": "ElicitationFormRequestMode",
    "ElicitationPropertySchema1": "ElicitationStringPropertySchema",
    "ElicitationPropertySchema2": "ElicitationNumberPropertySchema",
    "ElicitationPropertySchema3": "ElicitationIntegerPropertySchema",
    "ElicitationPropertySchema4": "ElicitationBooleanPropertySchema",
    "ElicitationPropertySchema5": "ElicitationMultiSelectPropertySchema",
    "ElicitationUrlMode1": "ElicitationUrlSessionMode",
    "ElicitationUrlMode2": "ElicitationUrlRequestMode",
    "NesSuggestion1": "NesEditSuggestionVariant",
    "NesSuggestion2": "NesJumpSuggestionVariant",
    "NesSuggestion3": "NesRenameSuggestionVariant",
    "NesSuggestion4": "NesSearchAndReplaceSuggestionVariant",
}

ENUM_LITERAL_MAP: dict[str, tuple[str, ...]] = {
    "PermissionOptionKind": (
        "allow_once",
        "allow_always",
        "reject_once",
        "reject_always",
    ),
    "PlanEntryPriority": ("high", "medium", "low"),
    "PlanEntryStatus": ("pending", "in_progress", "completed"),
    "StopReason": ("end_turn", "max_tokens", "max_turn_requests", "refusal", "cancelled"),
    "ToolCallStatus": ("pending", "in_progress", "completed", "failed"),
    "ToolKind": ("read", "edit", "delete", "move", "search", "execute", "think", "fetch", "switch_mode", "other"),
}

FIELD_TYPE_OVERRIDES: tuple[tuple[str, str, str, bool], ...] = (
    ("PermissionOption", "kind", "PermissionOptionKind", False),
    ("PlanEntry", "priority", "PlanEntryPriority", False),
    ("PlanEntry", "status", "PlanEntryStatus", False),
    ("PromptResponse", "stop_reason", "StopReason", False),
    ("ToolCall", "kind", "ToolKind", True),
    ("ToolCall", "status", "ToolCallStatus", True),
    ("ToolCallUpdate", "kind", "ToolKind", True),
    ("ToolCallUpdate", "status", "ToolCallStatus", True),
)