# fiber.infra.observer.intent.potential
## @lineage: fiber.dphi.infra.observer.intent.potential
import asyncio
import time
import json
import hashlib
from dataclasses import dataclass
from typing import Any, Dict, Optional

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519

from fiber.infra.config import dphi_env
from fiber.infra.adapter.settlement import MandateAdapter
from xphi.kernel.space.topos.workflow import ErrorMessage, StopMessage, Workflow, WorkflowMessage, step
from xphi.arch.event.next import generate_parity_triplet, next_phase_id
from xphi.arch.event.next import uuid4
from xphi.kernel.dphi.adapter.state import StateAdapter
from xphi.kernel.dphi.broker import DphiMethod
from xphi.watcher.plane.emitter import get_emitter
from xphi.kernel.phase.network.bridge import RpcBridge
from xphi.kernel.phase.inter.dvm import DvmInterpreter

log = get_emitter("intent.potential")


# =========================================================================
# 1. CORE ENTITIES & BRIDGES (Ported from intent.exchange)
# =========================================================================

class NodeIdentity:
    """Pure consensus participant entity in the protocol core (Ed25519-based)."""
    def __init__(self):
        self.key = ed25519.Ed25519PrivateKey.generate()
        self.pub_hex = self.key.public_key().public_bytes(
            encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw
        ).hex()
        # [FIX] 워크플로우에서 EVM 호환 주소 참조를 위해 Dummy EVM Address 생성 로직 추가
        self.evm_address = "0x" + self.pub_hex[:40]

    def sign(self, canonical_bytes: bytes) -> str:
        return self.key.sign(hashlib.sha256(canonical_bytes).digest()).hex()


class DvmRpcBridge(RpcBridge):
    """Orchestrates the DVM (revm/cosmwasm) for deterministic state derivation and validation."""
    def __init__(self):
        super().__init__()
        self.log = get_emitter("dvm.bridge")

    async def request(self, payload: Dict[str, Any], timeout: float = 5.0) -> Dict[str, Any]:
        action = payload.get("action")
        await asyncio.sleep(0.05)

        if action == DphiMethod.INIT_EPOCH.value:
            mandate_result = payload.get("mandate", {})
            actual_mandate = mandate_result.get("mandate", {})
            constraints = actual_mandate.get("constraints", {})
            
            if constraints.get("expiration_ts", 0) < int(time.time() * 1000):
                self.log.warning("🛑 [REJECTED] Ingress Validation Failed: AP2 Mandate Expired")
                return {"status": 401, "error": "Unauthorized: AP2 Mandate Expired"}
                
            topo = payload.get("topo", 0)
            press = payload.get("press", 0)
            return {"status": 200, "data": {"phase_id": next_phase_id(topo=topo, press=press)}}
            
        elif action == "simulate_vm":
            self.log.info("🔬 [DVM Engine] Initiating sandbox execution for state derivation...")
            vm_args = payload.get("payload", {})
            try:
                with DvmInterpreter(wasm_module_name="dvm.wasm") as dvm:
                    res = dvm.execute(
                        vm_target=vm_args.get("vm_target", "EVM"),
                        target_address=vm_args.get("target_address", "0x00"),
                        calldata=vm_args.get("calldata", "0x"),
                        state_snapshot=vm_args.get("state_snapshot", {}),
                        context={"caller": vm_args.get("caller_address"), "gas_price": hex(10**9), "value": "0x0"}
                    )
                    if res.success:
                        self.log.info("✅ [DVM Engine] State derivation successful.")
                        return {"status": 200, "data": json.loads(res.output)}
                    else:
                        self.log.error(f"🛑 [DVM Reverted] Execution Halted: {res.error}")
                        return {"status": 200, "data": {"success": False, "revert_reason": str(res.error)}}
            except Exception as e:
                self.log.error(f"💥 [DVM Fatality] Wasmtime Engine Exception: {e}")
                return {"status": 500, "error": str(e)}
            
        elif action == DphiMethod.SEAL_EPOCH.value:
            return {"status": 200, "data": {"hash": f"sealed_{uuid4().hex[:16]}", "receipt_id": f"nexus_receipt_{uuid4().hex[:8]}"}}
            
        return {"status": 404, "error": f"Unknown action: {action}"}


# =========================================================================
# 2. INTENT DOMAIN ENTITIES
# =========================================================================

@dataclass
class PsiArtifact:
    """
    [Preserved Heuristic State] 
    The initial, non-deterministic execution trajectory generated by the stochastic model.
    """
    suggested_target: str       
    suggested_calldata: str     

@dataclass
class ToposIntent:
    """
    [Invariant State Transition Vector] 
    Defines the pure objective manifold of the state transition.
    """
    event_id: str
    target_vm: str             
    input_asset: str           
    target_asset: str          
    expected_spread: int       
    artifact: PsiArtifact      


# =========================================================================
# 3. WORKFLOW MESSAGES & ORCHESTRATION
# =========================================================================

class IntentIngressMsg(WorkflowMessage): pass
class ShadowSyncMsg(WorkflowMessage): pass
class DvmObservationMsg(WorkflowMessage): pass
class EpochSealMsg(WorkflowMessage): pass
class IntentRecalibrateMsg(WorkflowMessage): pass

class TopologicalIntentWorkflow(Workflow):
    def __init__(self, intent: ToposIntent):
        super().__init__(name=f"TOPO_INTENT [{intent.event_id[:8]}]")
        self.log = log
        self.intent = intent
        self.rpc_bridge = DvmRpcBridge()
        
        self.field_node = NodeIdentity()
        self.shadow_state: Dict[str, Any] = {}
        self.dvm_state_diff: Dict[str, Any] = {}
        
        self.optimal_target: Optional[str] = None
        self.optimal_calldata: Optional[str] = None
        
        self.profit_margin: int = 0
        self.sealed_receipt: Optional[Dict[str, Any]] = None
        self.capability_receipt_id: Optional[str] = None

    async def start(self) -> bool:
        self.log.info(f"[INGRESS] Mapping intent topology: {self.intent.event_id}. Formulating Mandate...")
        self.post_message(IntentIngressMsg())
        await self.run()
        return self.sealed_receipt is not None

    @step
    async def phase_billing_handshake(self, msg: IntentIngressMsg) -> WorkflowMessage:
        self.log.info("[PHASE 0] Authorizing Deferred Billing Mandate to DPHI Edge.")
        
        ap2_mandate = MandateAdapter.build_ap2_mandate(
            requester_id=self.field_node.evm_address,
            target_action="shadow_execution",
            max_spend_usdc="100.0",
            signer_key=self.field_node.key
        )
        
        # DPHI RPC(또는 Edge API)에 Mandate 제출
        init_payload = {
            "action": DphiMethod.INIT_EPOCH.value,
            "topo": 120, "press": 85,
            "mandate": ap2_mandate.model_dump(exclude_none=True)
        }
        
        res = await self.rpc_bridge.request(init_payload)
        if res.get("status") != 200:
            return ErrorMessage(f"Mandate Rejected. Insufficient clearance: {res.get('error')}")
            
        self.capability_receipt_id = res.get("data", {}).get("phase_id", "mock_receipt_123")
        self.log.info(f"  └─ Capability Token Acquired: {self.capability_receipt_id}")
        
        return ShadowSyncMsg()

    @step
    async def phase_shadow_projection(self, msg: ShadowSyncMsg) -> WorkflowMessage:
        self.log.info("[PHASE 1] Projecting external state space onto local shadow manifold.")
        
        self.shadow_state = {
            self.intent.artifact.suggested_target: { "balance": "0x_latest_pool_balance", "nonce": 0 },
            self.field_node.pub_hex: { "balance": "0x_mock_jit_liquidity", "nonce": 1 }
        }
        return DvmObservationMsg()

    @step
    async def phase_dvm_solver(self, msg: DvmObservationMsg) -> WorkflowMessage:
        self.log.info("[PHASE 2] Evaluating heuristic artifact against deterministic boundary conditions.")
        
        dvm_payload_hypothesis = {
            "vm_target": self.intent.target_vm,
            "payload": {
                "target_address": self.intent.artifact.suggested_target,
                "calldata": self.intent.artifact.suggested_calldata,
                "gas_limit": 500000,
                "state_snapshot": self.shadow_state
            }
        }
        
        res = await self.rpc_bridge.request({
            "action": "simulate_vm", 
            "payload": dvm_payload_hypothesis,
            "billing_receipt": self.capability_receipt_id
        })
        
        data = res.get("data", {})
        self.profit_margin = int(data.get("state_diff", {}).get("agent_profit_delta", "0x0"), 16)
        
        if res.get("status") != 200 or self.profit_margin < self.intent.expected_spread:
            self.log.warning("[ARTIFACT DEVIATION] Heuristic failed boundary constraints. Initiating deterministic solver for re-calibration...")
            
            recalc_res = await self.rpc_bridge.request({
                "action": "solve_optimal_path",
                "intent": {
                    "input": self.intent.input_asset,
                    "target": self.intent.target_asset,
                    "snapshot": self.shadow_state
                },
                "billing_receipt": self.capability_receipt_id
            })
            
            if not recalc_res.get("data", {}).get("success"):
                return ErrorMessage("Topological constraints violated: No mathematical path exists within current state bounds.")
                
            data = recalc_res.get("data")
            self.profit_margin = int(data.get("state_diff", {}).get("agent_profit_delta", "0x0"), 16)
            
            self.optimal_target = data.get("optimal_target")
            self.optimal_calldata = data.get("optimal_calldata")
        else:
            self.log.info("[ARTIFACT CONVERGENCE] Heuristic trajectory aligns perfectly with deterministic invariants.")
            self.optimal_target = self.intent.artifact.suggested_target
            self.optimal_calldata = self.intent.artifact.suggested_calldata

        self.dvm_state_diff = data.get("state_diff", {})
        return EpochSealMsg()

    @step
    async def phase_epoch_seal(self, msg: EpochSealMsg) -> WorkflowMessage:
        self.log.info("[PHASE 3] Cryptographic entanglement of phase transition invariants.")
        
        parity = generate_parity_triplet(topo=120, press=85)
        
        seal_payload = StateAdapter.build_seal_epoch_payload(
            parity=parity, 
            parent_nexus_id=0, 
            self_parent_state="genesis",
            repos={
                "intent_id": self.intent.event_id,
                "heuristic_artifact": self.intent.artifact.__dict__,
                "deterministic_vector": self.optimal_calldata,
                "billing_receipt_used": self.capability_receipt_id 
            }, 
            cached_states={"state_differential": self.dvm_state_diff},
            timestamp=time.time(), 
            signers=[], signatures=[], threshold=0
        )
        
        res = await self.rpc_bridge.request({
            "action": DphiMethod.SEAL_EPOCH.value, 
            "payload": StateAdapter.to_canonical_bytes(seal_payload).decode('utf-8')
        })
        
        if res.get("status") != 200:
            return ErrorMessage(f"Seal generation rejected: {res.get('error')}")
            
        self.sealed_receipt = res.get("data", {})
        return IntentRecalibrateMsg()

    @step
    async def phase_private_relay(self, msg: IntentRecalibrateMsg) -> WorkflowMessage:
        self.log.info("[PHASE 4] Relaying conditioned state transition payload to private execution topology.")
        
        relay_payload = {
            "sealed_hash": self.sealed_receipt.get("hash"),
            "target_address": self.optimal_target,
            "calldata": self.optimal_calldata,
            "execution_condition": {
                "min_profit": self.intent.expected_spread
            }
        }
        
        self.log.info("[RELAY] Dispatching hardened topological payload to isolated consensus network.")
        self.log.info("[FINALITY] Topological phase transition complete. State differential matrix materialized.")
        return StopMessage(result=True)

    @step
    async def on_error(self, msg: ErrorMessage) -> WorkflowMessage:
        self.log.error(f"[HALT] Preserving non-convergent state vectors for heuristic re-calibration: {msg.msg}")
        return StopMessage(result=False)