# dphi.exchange.intent
import asyncio
import time
import json
from dataclasses import dataclass
from typing import Any, Dict, Optional

from dphi.adapter.config.dphi import mock_env
from dphi.adapter.eco import EcoAdapter
from dphi.exchange.workflow import DvmRpcBridge, NodeIdentity

from arch.topos.workflow import ErrorMessage, StopMessage, Workflow, WorkflowMessage, step
from arch.contract.event.next import generate_parity_triplet
from kernel.dphi.adapter.state import StateAdapter
from kernel.dphi.broker import DphiMethod
from watcher.plane.emitter import get_emitter

log = get_emitter("workflow.intent")

@dataclass
class PsiEvent:
    """Micro-mutation vector generated by the Local 8B Model."""
    event_id: str
    target_vm: str             # "EVM" or "COSMWASM"
    target_address: str        # e.g., Uniswap Pool or CW20 Contract
    calldata_vector: str       # Hex payload for the execution
    expected_spread: int       # Minimum profit threshold expected by the 8B model

class IntentIngressMsg(WorkflowMessage): pass
class ShadowSyncMsg(WorkflowMessage): pass
class DvmObservationMsg(WorkflowMessage): pass
class EpochSealMsg(WorkflowMessage): pass

class IntentMatchingWorkflow(Workflow):
    """
    Pipeline for Stochastic Intent Matching.
    Filters raw PsiEvents through the deterministic DVM sandbox. 
    Only structurally valid and profitable state differentials are synced to external ledgers.
    """
    def __init__(self, psi_event: PsiEvent):
        super().__init__(name=f"INTENT_MATCH [{psi_event.event_id[:8]}]")
        self.log = log
        self.psi_event = psi_event
        self.rpc_bridge = DvmRpcBridge()
        
        self.field_node = NodeIdentity()
        self.shadow_state: Dict[str, Any] = {}
        self.dvm_state_diff: Dict[str, Any] = {}
        self.profit_margin: int = 0
        self.sealed_receipt: Optional[Dict[str, Any]] = None

    async def start(self) -> bool:
        self.log.info(f"▶️ [INGRESS] Processing PsiEvent: {self.psi_event.event_id} | Target: {self.psi_event.target_vm}")
        self.post_message(IntentIngressMsg())
        await self.run()
        return self.sealed_receipt is not None

    @step
    async def phase_shadow_projection(self, msg: IntentIngressMsg) -> WorkflowMessage:
        self.log.info("--- [Phase 1] Shadow State Projection (JIT Liquidity Injection) ---")
        
        # 물리적 외부 원장(Dumb DB)의 최신 상태를 읽어와 섀도우 복제본 생성
        # (JIT 차익거래를 위해 가상의 에이전트 잔고를 스냅샷에 주입)
        self.shadow_state = {
            self.psi_event.target_address: {
                "balance": "0x_latest_pool_balance",
                "nonce": 0
            },
            self.field_node.pub_hex: {
                "balance": "0x_mock_jit_liquidity",  # JIT 유동성 강제 주입
                "nonce": 1
            }
        }
        return ShadowSyncMsg()

    @step
    async def phase_dvm_observation(self, msg: ShadowSyncMsg) -> WorkflowMessage:
        self.log.info("--- [Phase 2] Deterministic Sandbox Observation (DVM Pre-flight) ---")
        
        dvm_payload = {
            "vm_target": self.psi_event.target_vm,
            "payload": {
                "target_address": self.psi_event.target_address,
                "calldata": self.psi_event.calldata_vector,
                "gas_limit": 500000,
                "state_snapshot": self.shadow_state
            }
        }
        
        # 8B 모델의 맹목적 추론값을 DVM의 물리법칙(Fuel, Revert)에 충돌시킴
        res = await self.rpc_bridge.request({"action": "simulate_vm", "payload": dvm_payload})
        data = res.get("data", {})
        
        if res.get("status") != 200 or not data.get("success"):
            # 🌟 [Brute-force Natural Selection]
            # 8B 모델이 뱉어낸 이벤트가 문법 오류이거나 슬리피지(Spread) 부족으로 DVM에서 Revert 발생.
            # 외부 체인에 수수료를 낭비하지 않고 즉각(0 ms) 비용 없이 폐기.
            self.log.info(f"🛑 [MUTATION REJECTED] DVM Halted: {data.get('revert_reason', 'Execution Trap')}")
            return StopMessage(result=False)

        self.dvm_state_diff = data.get("state_diff", {})
        
        # 상태 변이분(state_diff)에서 수익성 수학적 검증
        self.profit_margin = int(self.dvm_state_diff.get("agent_profit_delta", "0x0"), 16)
        if self.profit_margin < self.psi_event.expected_spread:
            self.log.warning(f"⚠️ [PROFIT REJECTED] Yield ({self.profit_margin}) < Threshold ({self.psi_event.expected_spread})")
            return StopMessage(result=False)

        self.log.info(f"✅ [OBSERVATION PASSED] State collapse determined positive yield: {self.profit_margin}")
        return DvmObservationMsg()

    @step
    async def phase_epoch_seal(self, msg: DvmObservationMsg) -> WorkflowMessage:
        self.log.info("--- [Phase 3] Cryptographic Epoch Sealing ---")
        
        # 검증된 상태 변이분을 얽힘(Entangled) 상태로 패키징
        parity = generate_parity_triplet(topo=120, press=85)
        seal_payload = StateAdapter.build_seal_epoch_payload(
            parity=parity, 
            parent_nexus_id=0, 
            self_parent_state="genesis",
            repos={"psi_event": self.psi_event.event_id}, 
            cached_states={"state_diff": self.dvm_state_diff},
            timestamp=time.time(), 
            signers=[], signatures=[], threshold=0
        )
        
        res = await self.rpc_bridge.request({
            "action": DphiMethod.SEAL_EPOCH.value, 
            "payload": StateAdapter.to_canonical_bytes(seal_payload).decode('utf-8')
        })
        
        if res.get("status") != 200:
            return ErrorMessage(f"Core Ledger Commit Rejected: {res.get('error')}")
            
        self.sealed_receipt = res.get("data", {})
        return EpochSealMsg()

    @step
    async def phase_ledger_sync(self, msg: EpochSealMsg) -> WorkflowMessage:
        self.log.info("--- [Phase 4] External Ledger Synchronization (Dumb DB Write) ---")
        # 🌟 로컬에서 무결성과 수익이 100% 확정된 상태를 외부 이더리움/코스모스 원장에 동기화(Sync)
        # 로직 연산이 아닌 단순 I/O 작업으로 전락
        
        self.log.info(f"🚀 [SYNC] Dispatching validated payload to {self.psi_event.target_vm} mempool...")
        # e.g., await self.wallet_client.broadcast_transaction(self.psi_event.calldata_vector)
        
        self.log.info(f"🎉 [FINALITY] Profit Matrix Materialized. Sequence Terminated.")
        return StopMessage(result=True)

    @step
    async def on_error(self, msg: ErrorMessage) -> WorkflowMessage:
        self.log.error(f"❌ [HALTED] Pipeline execution terminated: {msg.msg}")
        return StopMessage(result=False)